#index:
#    path: /
#    controller: App\Controller\DefaultController::index
controllers:
    resource: ../src/Controller/
    type: annotation

admin:
    prefix: /admin
    resource: ../src/Controller/Admin
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation